### ISSUE TITLE
Google Colab support

### ISSUE THREAD

**Issue by orenelbaum** [wellecks/llmstep#6]
Any chance for Colab support for those of us without a GPU?
As a beginner I'm eager to try this out, I feel like it could be really useful, but can't run it locally.

**Comment by wellecks** [comment]
Hi, that's a great idea. It looks like it's possible: https://colab.research.google.com/drive/1r-yJC6erO5qn_WlmIpDpxnPmO3ZO2mf9

This will start a server, then you want to set the host to the one that's printed out, and the port to 80. E.g. in the example:
```
export LLMSTEP_HOST="81ba-34-87-62-26.ngrok.io"
export LLMSTEP_PORT=80
```
(these are used by `suggest.py`). Make sure to pull from master since I just added in the LLMSTEP_HOST variable.

**Comment by wellecks** [comment]
I'll clean up the example and add it to the repo when I have the chance

**Comment by wellecks** [comment]
@orenelbaum colab is supported now, please see the README. Thanks for the great suggestion!

**Comment by orenelbaum** [comment]
Awesome, thanks!
